blog/urls.py
from django.urls import path, include
from . import views
from .feeds import RssBlogFeed, AtomBlogFeed
from .views import search, PostViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'api', PostViewSet)


app_name = 'blog'
urlpatterns = [
    path('', views.most_viewed, name='most_viewed'),
    path('contact/', views.contact_page, name='contact_page'),
    path('articles/', views.post_list, name='post_list'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('subscribe/confirm/', views.subscription_confirmation,
         name='subscription_confirmation'),
    path('unsubscribe/', views.unsubscribe, name='unsubscribe'),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('blog/<int:year>/<int:month>/<int:day>/<str:post>/',
         views.post_detail, name='post_detail'),
    path('preview/<int:id>/', views.preview, name="preview"),
    path('feed/rss/', RssBlogFeed(), name='rss_feed'),
    path('feed/atom/', AtomBlogFeed(), name='atom_feed'),
    path('about/', views.about_page, name='about'),
    path('author/<str:post_author>/', views.post_author, name="post_author"),
    path('search', search, name='search'),
    path('me/', views.me, name='me'),
    path('', include(router.urls)),
    path('captcha/', include('captcha.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('offline/', views.offline, name='offline'),
    path('sw.js', views.ServiceWorkerView.as_view(),
         name=views.ServiceWorkerView.name,),
]

ojas/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from blog.sitemaps import PostSitemap
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'blog.views.error_404'
handler500 = 'blog.views.error_500'
handler403 = 'blog.views.error_403'
handler400 = 'blog.views.error_400'


sitemaps = {
    'static': PostSitemap,
}


urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment
from captcha.fields import CaptchaField


class CommentForm(forms.ModelForm):

    name = forms.CharField(label='Enter your name/email', max_length=100, required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Optional', 'class': 'p-2 rounded border border-gray-200 bg-white dark:border-gray-700 text-gray-600 dark:text-gray-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-teal-400 focus:border-transparent placeholder-gray-400 text-sm h-auto',
    }))

    body = forms.CharField(label='Enter your message', max_length=500, widget=forms.Textarea(attrs={
        'placeholder': '500 characters max', 'class': 'p-2 rounded border border-gray-8 bg-white dark:border-gray-700 text-gray-600 dark:text-gray-800 focus:bg-white focus:outline-none focus:ring-2 focus:ring-teal-400 focus:border-transparent placeholder-gray-400 text-sm h-auto', 'rows': '3', 'cols': '32',
    }))

    captcha = CaptchaField(label='Verify you are a human')

    class Meta:
        model = Comment
        fields = ('name',  'captcha', 'body',)

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Author, Viewer, Admin, Subscriber
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.template.loader import get_template
from django.views.generic import TemplateView
from django.templatetags.static import static
from django.core.exceptions import BadRequest
from django.core.mail import EmailMessage
from datetime import datetime, timedelta
from .serializers import PostSerializer
from django.db.models import Count, Q
from django.contrib import messages
from rest_framework import viewsets
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from .forms import CommentForm
from taggit.models import Tag
from ojas import version
import logging
import traceback
import secrets
import string
logger = logging.getLogger(__name__)
domain = settings.ALLOWED_HOSTS[0]
logo_url = settings.LOGO_URL


def offline(request):
    """
    Returns offline/fallback page whenever user's internet connection is broken
    """
    return render(request, 'offline.html')


def get_ip(request):
    """
    Returns the IP of the user
    """
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def error_400(request, exception):
    """
    Returns the custom Bad Request Error view
    """
    err = {
        'code': 'Error 400',
        'msg': exception,
    }
    return render(request, 'error.html', {'err': err})


def error_404(request, exception):
    """
    Returns the custom Not Found Error view
    """
    data = {}
    return render(request, '404.html', data)


def error_403(request, exception):
    """
    Returns the custom PermissionDenied Error view
    """
    err = {
        'code': 'Error 403',
        'msg': 'Permission Denied',
    }
    return render(request, 'error.html', {'err': err})


def error_500(request):
    """
    Returns the custom Server Error view
    """
    err = {
        'code': 'Error 500',
        'msg': 'Server Error',
    }
    return render(request, 'error.html', {'err': err})


def about_page(request):
    """
    Returns the about page
    """
    data = {}
    return render(request, 'about.html', data)


def contact_page(request):
    """
    Returns the contact page
    """
    admin = Admin.objects.first()
    return render(request, 'contact.html', {'admin': admin})


def me(request):
    """
    Returns the know your details page
    """
    if request.user_agent.is_mobile:
        device = 'mobile'
    if request.user_agent.is_tablet:
        device = 'tablet'
    if request.user_agent.is_pc:
        device = 'pc'
    me = {
        'device': device,
        'bot': request.user_agent.is_bot,
        'touch': request.user_agent.is_touch_capable,
        'browser': request.user_agent.browser.family,
        'browser_version': request.user_agent.browser.version_string,
        'ip': get_ip(request),
        'os': request.user_agent.os.family,
        'time': datetime.now(),
        'device_name': request.user_agent.device.family,
    }

    return render(request, 'me.html', {'me': me})


def send_subscription_mail(email, confirmation_url):
    """
    Sends an email to the reader containing the confirmation link
    """
    ctx = {
        'confirmation_url': confirmation_url,
        'logo_url': logo_url,
        'domain': domain,
    }
    message = get_template('admin/subscription.html').render(ctx)
    msg = EmailMessage(
        'Please Confirm Your Subscription',
        message,
        'contactahampriyanshu@gmail.com',
        [email],
    )
    msg.content_subtype = "html"
    try:
        msg.send()
        logger.info("Email " + email + " successfully")
        return True
    except Exception as e:
        logger.error("Error ocuured while sending email to " +
                     email + " : " + e)
        return False


def send_confirmation_mail(email, unsubsrcibe_url):
    """
    Sends an email to the reader thanking him/her for confirmimng the subscription
    """
    ctx = {
        'unsubsrcibe_url': unsubsrcibe_url,
        'logo_url': logo_url,
        'domain': domain,
    }
    message = get_template('admin/confirmation.html').render(ctx)
    msg = EmailMessage(
        'Thank you for the confirmation',
        message,
        'contactahampriyanshu@gmail.com',
        [email],
    )
    msg.content_subtype = "html"
    try:
        msg.send()
        logger.info("Email " + email + " successfully")
        return True
    except Exception as e:
        logger.error("Error ocuured while sending email to " +
                     email + " : " + e)
        return False


def send_unsubscription_confirmation_mail(email):
    """
    Sends a farewell email to the reader after he/she unsubscribes
    """
    ctx = {
        'logo_url': logo_url,
        'domain': domain,
    }
    message = get_template('admin/unsubscribe.html').render(ctx)
    msg = EmailMessage(
        'Unsubscribed Successfully',
        message,
        'contactahampriyanshu@gmail.com',
        [email],
    )
    msg.content_subtype = "html"
    try:
        msg.send()
        logger.info("Email " + email + " successfully")
        return True
    except Exception as e:
        logger.error("Error ocuured while sending email to " +
                     email + " : " + e)
        return False


def subscription_confirmation(request):
    """
    Handle all the event after user click the confirmation link
    """
    message = dict()
    if "POST" == request.method:
        ip = get_ip(request)
        logger.warn(
            "User with IP : " + str(ip) + " made an inavlid request")
        raise BadRequest('Bad Request Method')
    token = request.GET.get("token", None)
    if token:
        try:
            subscribe_model_instance = Subscriber.objects.get(token=token)
            new_token = ''.join(secrets.choice(
                string.ascii_uppercase + string.digits) for i in range(128))
            subscribe_model_instance.confirmed = True
            subscribe_model_instance.token = str(new_token)
            email = subscribe_model_instance.email
            unsubsrcibe_url = request.build_absolute_uri(
                reverse('blog:unsubscribe')) + "?token=" + new_token + "&email=" + email
            send_confirmation_mail(email, unsubsrcibe_url)
            subscribe_model_instance.save()
            messages.success(request, "Subscription Confirmed. Thank you.")
            message['status'] = 'Yeah! Subscription Confirmed'
            message['msg'] = 'I will be sending you the latest articles once or twice a month.'
            message['instruction'] = 'Thank you'
            logger.info(email + " subscribed successfully")
        except Subscriber.DoesNotExist as e:
            message['status'] = 'Unknown error occured'
            message['msg'] = 'Check your internet connection'
            message['instruction'] = 'Please try reopening the link'
            logger.warning(traceback.format_exc())
    else:
        message['status'] = 'Invalid token'
        message['msg'] = 'Check your internet connection'
        message['instruction'] = 'Please try reopening the link'
        logger.warning("Invalid token ")
        messages.error(request, "Invalid Link")

    return render(request, 'admin/status.html', {'message': message})


def unsubscribe(request):
    """
    Handle all the event after user click the unsubscribe link
    """
    message = dict()

    if "POST" == request.method:
        ip = get_ip(request)
        logger.warn(
            "User with IP : " + str(ip) + " made an inavlid request")
        raise BadRequest('Bad Request Method')

    token = request.GET.get("token", None)
    email = request.GET.get("email", None)

    if token and email:
        try:
            subscribe_model_instance = Subscriber.objects.get(
                token=token, email=email)
            subscribe_model_instance.delete()
            send_unsubscription_confirmation_mail(email)
            message['status'] = 'Unsubscribed successfully'
            message['msg'] = 'Sorry to see you go :('
            message['instruction'] = 'Bye'
            logger.info(email + " unsubscribed successfully")
            messages.success(
                request, "Unsubscribed successfully. Sorry to see you go.")
        except Subscriber.DoesNotExist as e:
            message['status'] = 'Unknown error occured'
            message['msg'] = 'Check your internet connection'
            message['instruction'] = 'Please try reopening the link'
            logger.warning(traceback.format_exc())
            messages.error(request, "Invalid Link")
    else:
        logger.error("Error occured while " + email + " was unsubscribing")
        messages.error(request, "Invalid Link")
        message['status'] = 'Invalid token or email'
        message['msg'] = 'Check your internet connection'
        message['instruction'] = 'Please try reopening the link'
    return render(request, 'admin/status.html', {'message': message})


def subscribe(request):
    """
    Handle all the event once the user has entered a valid email address
    """
    message = dict()
    post_data = request.POST.copy()
    email = post_data.get("email", None)
    token = ''.join(secrets.choice(string.ascii_uppercase +
                    string.digits) for i in range(128))
    try:
        subscribe_model_instance = Subscriber.objects.get(email=email)
        message['status'] = 'Email entered already exist'
        message['msg'] = 'Search your inbox for confirmation mail'
        message['instruction'] = 'You may also contact the admin'
    except Subscriber.DoesNotExist:
        confirmation_url = request.build_absolute_uri(

blog/templates/article.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    <!-- articles -->
    <div class="container mt-6 md:mt-12 mx-auto py-4 md:px-12 lg:w-10/12 ">
        <div class="flex flex-wrap justify-center">
            {% for post in posts %}
                <div class="my-1 px-1 w-full md:w-1/2 md:my-2 md:px-2 flex flex-col justify-between lg:my-4 lg:px-4 lg:w-1/3 ">
                    <div class="overflow-hidden bg-gray-50 md:bg-white  md:shadow-lg dark:bg-gray-900 md:dark:bg-gray-800 md:rounded-lg md:shadow-lg">
                        <div class="p-2 md:p-0">
                            <a href="{{ post.get_absolute_url }}">
                                {% if post.image %}
                                    <img alt="Post Image" class="overflow-hidden block object-cover rounded-lg md:rounded-none h-48 w-full" src="{{ post.image.url }}">
                                    {% else %}
                                        <img alt="Post Image" class="overflow-hidden block object-cover rounded-lg md:rounded-none h-48 w-full" src="{% static 'default/blog.png' %}">
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="md:h-48">
                                    <div class="overflow-hidden h-32 p-4 mb-3">
                                        <a href="{{ post.get_absolute_url }}">
                                            <p class="truncate font-semibold leading-7 text-gray-600 dark:text-gray-200 text-lg mb-2">{{ post.title }}</p>
                                            <div class="break-words text-sm text-gray-600 dark:text-gray-400">
                                                <p>{{ post.body|markdown|truncatewords_html:20 }}</p>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="mb-5 flex items-center justify-between leading-none mx-3">
                                        <a href='{% url "blog:post_author" post.author %}'>
                                            <div class="flex items-center ml-2">
                                                <img class="overflow-hidden w-10 h-10 rounded p-1" src="{{ post.author.image.url }}" alt="autor image">
                                                    <div class="text-xs ml-2 text-left text-gray-600 dark:text-gray-400">
                                                        <p>{{ post.author }}</p>
                                                        <p>{{ post.publish|date:"d M, Y" }}</p>
                                                    </div>
                                                </div>
                                            </a>
                                            <div class="text-sm text-left text-gray-600 dark:text-gray-400 px-8 py-2">
                                                <p>
                                                    {{ post.body|safe|read }}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% empty %}
                            <p class="text-sm my-10 text-gray-600 dark:text-gray-400 text-center">We may need some more articles</p>
                        {% endfor %}
                    </div>
                    {% include "pagination.html" with page=posts %}
                </div>
            {% endblock content %}

blog/templates/common_tags.html
{% for tag in tags %}
    <li>
        <a class="text-gray-600 dark:text-gray-400 hover:underline py-1 text-sm" href='{% url "blog:post_list_by_tag" tag.slug %}'>{{ tag }}</a>
    </li>
{% endfor %}

blog/templates/footer.html
{% load custom_tags %}
{% load static %}
{% block content %}
    <footer class="font-sans relative pt-5 pb-3 md:pb-6">
        <div class="container mx-auto px-4">
            <div class="flex flex-wrap">
                <div class="flex w-full md:w-5/12">
                    <div class="text-2xl px-4">
                        {% get_about %}
                    </div>
                </div>
                <div class="flex w-full md:w-5/12 px-4">
                    <div class="text-2xl">
                        <p class="font-bold text-gray-900 dark:text-gray-100">Subsrcibe</p>
                        <p class="mt-2 mb-4 text-gray-600 dark:text-gray-400 text-sm">Get the latest posts delivered right to your inbox</p>
                        <div class="my-4">
                            <form id="footerForm" action="{% url 'blog:subscribe' %}" method="POST" class="form-horizontal">
                                {% csrf_token %}
                                <input type="email" name="email" size="14" class="p-2 border border-grey-light rounded text-black placeholder-gray-400 text-sm h-auto
                                        focus:bg-white focus:outline-none focus:ring-2 focus:ring-teal-400 focus:border-transparent" placeholder="Enter Email Address" required="required">
                                    <input type="submit" id="emailBtn" value="Subscribe" class="bg-teal-500 text-white active:bg-teal-400
                                            rounded shadow hover:shadow-lg outline-none focus:outline-none h-auto text-xs p-3"></form>
                                </div>
                            </div>
                        </div>
                        <div class="flex w-full md:w-2/12 px-4">
                            <div class="flex flex-wrap items-top">
                                <div class="w-full  ml-auto">
                                    <p class="font-bold text-2xl text-gray-900 dark:text-gray-100">Popular Tags</p>
                                    <ul class="list-unstyled mt-2 mb-4">
                                        {% common_tags 4 %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr class="my-3 md:my-6 border-gray-400"/>
                    <div class="flex flex-wrap items-center md:justify-between justify-center">
                        <div class="w-full md:w-4/12 px-4 mx-auto text-center">
                            <div class="text-sm text-gray-600 dark:text-gray-400 py-1">
                                &copy;
                                <span id="year"></span>
                                <a href="https://github.com/ahampriyanshu" class="hover:underline hover:text-gray-900">{%  get_author %}</a>.
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        {% endblock content %}

blog/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    <!-- articles -->
    <div class="container mt-6 md:mt-12 mx-auto py-4 md:px-12 lg:w-10/12 ">
        <div class="flex flex-wrap justify-center">
            {% for post in posts %}
                <div class="my-1 px-1 w-full md:w-1/2 md:my-2 md:px-2 flex flex-col justify-between lg:my-4 lg:px-4 lg:w-1/3 ">
                    <div class="overflow-hidden bg-gray-50 md:bg-white  md:shadow-lg dark:bg-gray-900 md:dark:bg-gray-800 md:rounded-lg md:shadow-lg">
                        <div class="p-2 md:p-0">
                            <a href="{{ post.get_absolute_url }}">
                                {% if post.image %}
                                    <img alt="Post Image" class="overflow-hidden block object-cover rounded-lg md:rounded-none h-48 w-full" src="{{ post.image.url }}">
                                    {% else %}
                                        <img alt="Post Image" class="overflow-hidden block object-cover rounded-lg md:rounded-none h-48 w-full" src="{% static 'default/blog.png' %}">
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="md:h-48">
                                    <div class="overflow-hidden h-32 p-4 mb-3">
                                        <a href="{{ post.get_absolute_url }}">
                                            <p class="truncate font-semibold leading-7 text-gray-600 dark:text-gray-200 text-lg mb-2">{{ post.title }}</p>
                                            <div class="break-words text-sm text-gray-600 dark:text-gray-400">
                                                <p>{{ post.body|markdown|truncatewords_html:20 }}</p>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="mb-5 flex items-center justify-between leading-none mx-3">
                                        <a href='{% url "blog:post_author" post.author %}'>
                                            <div class="flex items-center ml-2">
                                                <img class="overflow-hidden w-10 h-10 rounded p-1" src="{{ post.author.image.url }}" alt="author image">
                                                    <div class="text-xs ml-2 text-left text-gray-600 dark:text-gray-400">
                                                        <p>{{ post.author }}</p>
                                                        <p>{{ post.publish|date:"d M, Y" }}</p>
                                                    </div>
                                                </div>
                                            </a>
                                            <div class="text-sm text-left text-gray-600 dark:text-gray-400 px-8 py-2">
                                                <p>
                                                    {{ post.body|markdown|read }}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% empty %}
                            <p class="text-sm my-10 text-gray-600 dark:text-gray-400 text-center">We may need some more articles</p>
                        {% endfor %}
                    </div>
                    {% include "pagination.html" with page=posts %}
                </div>
            {% endblock content %}

blog/templates/most_commented.html
{% load static %}
{% load custom_tags %}
<div class="container w-full md:mt-4 mx-auto py-4 md:px-12">
    <p class="font-sans font-bold text-3xl mb-5 leading-none text-center text-gray-700 dark:text-gray-200">Most Discussed</p>
    <div class="max-w-full flex flex-wrap justify-center">
        {% for post in commented_posts %}
            <div class="w-full md:w-1/2 md:my-4 lg:px-4 md:flex mb-8">
                <a href='{{ post.get_absolute_url }}'>
                    <div class="md:h-64 h-auto md:w-48 flex-none rounded-t md:rounded-t-none md:rounded-l text-center">
                        <div class="p-4 md:p-0">
                            {% if post.image %}
                                <img class="overflow-hidden rounded md:rounded-none md:border md:border-r-0 md:dark:border-gray-600 h-auto md:rounded-l md:h-64" src="{{ post.image.url }}" alt="uploaded cover image"/>
                            {% else %}
                                <img class="overflow-hidden rounded md:rounded-none md:border md:border-r-0 md:dark:border-gray-600 h-auto md:rounded-l md:h-64" src="{% static 'default/blog.png' %}" alt="default cover image"/>
                            {% endif %}
                        </div>
                    </div>
                </a>
                <div class="overflow-hidden md:border md:border-l-0 md:dark:border-gray-600 rounded-r h-auto md:h-64 md:w-full p-2 flex flex-col
                                                        justify-between leading-normal bg-gray-50 md:bg-white dark:bg-gray-900 md:dark:bg-gray-800">
                    <div class="overflow-hidden mb-4 h-auto md:h-48 px-4 md:px-0">
                        <a href="{{ post.get_absolute_url }}">
                            <div class="truncate text-black font-bold text-gray-600 dark:text-gray-200 text-xl mb-2">{{ post.title }}</div>
                            <div class="hidden md:block break-words text-sm text-gray-600 dark:text-gray-400">
                                <p>{{ post.body|markdown|truncatewords_html:50 }}
                                </p>
                            </div>
                            <div class="block md:hidden break-words text-sm text-gray-600 dark:text-gray-400">
                                <p>{{ post.body|markdown|truncatewords_html:40 }}
                                </p>
                            </div>
                        </a>
                    </div>
                    <div class="flex items-center justify-between leading-none mx-3">
                        <a href='{% url "blog:post_author" post.author %}'>
                            <div class="flex items-center ml-2">
                                <img class="overflow-hidden w-10 h-10 rounded p-1" src="{{ post.author.image.url }}" alt="{{ post.author }} image">
                                    <div class="text-xs ml-2 text-left text-gray-600 dark:text-gray-400">
                                        <p>{{ post.author }}</p>
                                        <p>{{ post.publish|date:"d M, Y" }}</p>
                                    </div>
                                </div>
                            </a>
                            <div class="text-sm text-left text-gray-600 dark:text-gray-400 px-8 py-2">
                                <p>
                                    {{ post.body|safe|read }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <h2 class="text-sm my-10 text-gray-600 dark:text-gray-400 text-center">We may need some more articles</h2>
            {% endfor %}
        </div>
    </div>

blog/templates/search.html
{% extends 'base.html' %}
{% load custom_tags %}
{% load static %}
{% block content %}
    <p class="font-sans font-bold text-2xl md:text-4xl leading-none my-6 md:my-12 text-center text-gray-600 dark:text-gray-200">
        Search results for
        <span class="text-teal-500">{{ query }}</span>
    </p>
    {% for post in queryset %}
        <div class="mx-auto px-4 py-4 max-w-xl my-auto">
            <div class="bg-gray-50 md:bg-white md:shadow-xl md:rounded-lg mb-6">
                <a href='{{ post.get_absolute_url }}'>
                    <div class="">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" alt="uploaded cover image" class="overflow-hidden object-cover h-48 w-full md:h-full rounded-lg md:rounded-b-none">
                            {% else %}
                                <img src="{% static 'default/blog.png' %}" alt="default cover image" class="overflow-hidden object-cover h-48 w-full md:h-full rounded-lg md:rounded-b-none">
                                {% endif %}
                            </div>
                        </a>
                        <div class="bg-gray-50 md:bg-white md:shadow-lg dark:bg-gray-900 md:dark:bg-gray-800">
                            <a href='{{ post.get_absolute_url }}'>
                                <div class="p-4">
                                    <p class="truncate font-bold mb-2 md:mt-2 text-2xl text-gray-600 dark:text-gray-200 tracking-normal">{{ post.title }}</p>
                                    <div class="break-words text-sm text-gray-600 dark:text-gray-400 ">
                                        <p>{{ post.body|markdown|truncatewords_html:40 }}</p>
                                    </div>
                                </div>
                            </a>
                            <div class="flex items-center justify-between p-2 md:p-4 mx-2 md:mx-4">
                                <a href='{% url "blog:post_author" post.author %}'>
                                    <div class="flex items-center ml-2">
                                        <img class="overflow-hidden w-10 h-10 md:w-12 md:h-12 rounded " src="{{ post.author.image.url }}" alt="author image">
                                            <div class="text-xs ml-2 text-left text-gray-600 dark:text-gray-400">
                                                <p>{{ post.author }}</p>
                                                <p>{{ post.publish|date:"d M, Y" }}</p>
                                            </div>
                                        </div>
                                    </a>
                                    <div class="text-sm md:text-base text-left text-gray-600 dark:text-gray-400 px-8 py-2">
                                        <p>
                                            {{ post.body|markdown|read }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <h2 class="text-sm my-10 text-gray-600 dark:text-gray-400 text-center">No results were found</h2>
                {% endfor %}
            {% endblock %}